name: shopping
ingress:
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
  hosts:
    - host: shopping.ecommerce-store-builder.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: shopping-tls
      hosts:
        - shopping.ecommerce-store-builder.local