version: '3.8'

services:

###########################################################
######################## ingress ##########################
###########################################################

  ingress_public:
    ports:
      - "80:80"

###########################################################
######################## frontends ########################
###########################################################

  frontend_marketing:
    ports:
      - "8010:80"
    restart: always

  frontend_registration:
    environment:
      - HTTP_PORT=80
    ports:
      - "8020:80"
    restart: always

  frontend_shopping:
    environment:
      - HTTP_PORT=80
    ports:
      - "8030:80"
    restart: always

  frontend_management:
    environment:
      - HTTP_PORT=80
    ports:
      - "8040:80"
    restart: always

  frontend_admin:
    environment:
    - HTTP_PORT=80
    ports:
      - "8050:80"
    restart: always

###########################################################
######################## backends #########################
###########################################################

  backend_registration:
    environment:
      - HTTP_PORT=80
      - GRPC_PORT=81
    ports:
      - "6020:80"
      - "6021:81"
    restart: always

  backend_shopping:
    environment:
      - HTTP_PORT=80
      - GRPC_PORT=81
    ports:
      - "6030:80"
      - "6031:81"
    restart: always

  ###########################################################
  ######################## services #########################
  ###########################################################

  service_catalog:
    environment:
      - HTTP_PORT=80
      - GRPC_PORT=81
    ports:
      - "5010:80"
      - "5011:81"
    restart: always

  service_carts:
    environment:
      - HTTP_PORT=80
      - GRPC_PORT=81
    ports:
      - "5020:80"
      - "5021:81"
    restart: always

  service_media:
    environment:
      - HTTP_PORT=80
      - GRPC_PORT=81
    ports:
      - "5030:80"
      - "5031:81"
    restart: always

  service_search:
    environment:
      - HTTP_PORT=80
      - GRPC_PORT=81
    ports:
      - "5040:80"
      - "5041:81"
    restart: always

  service_stores:
    environment:
      - HTTP_PORT=80
      - GRPC_PORT=81
    ports:
      - "5050:80"
      - "5051:81"
    restart: always

  service_accounts:
    environment:
      - HTTP_PORT=80
      - GRPC_PORT=81
    ports:
      - "5060:80"
      - "5061:81"
    restart: always
