name: management
environment:
ingress:
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
  hosts:
    - host: management.ecommerce-store-builder.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: management-tls
      hosts:
        - management.ecommerce-store-builder.local