name: management
ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
  hosts:
    - host: management.ecommerce-store-builder.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: management-tls
      hosts:
        - management.ecommerce-store-builder.com