name: marketing
ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
  hosts:
    - host: marketing.ecommerce-store-builder.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: marketing-tls
      hosts:
        - marketing.ecommerce-store-builder.dev