name: marketing
environment:
ingress:
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
  hosts:
    - host: marketing.ecommerce-store-builder.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: marketing-tls
      hosts:
        - marketing.ecommerce-store-builder.local