name: "Push Docker Image"
description: "Pushes a docker image for a single component"

inputs:
  component:
    description: "Component to push e.g. service_carts"
    required: true
  image_name:
    description: "Name of image"
    required: true
  registry_host:
    description: "Image registry host e.g. ghcr.io"
    required: true
  registry_endpoint:
    description: "Image registry repo e.g. ghcr.io/saas"
    required: true
  registry_username:
    description: "Registry username"
    required: true
  registry_password:
    description: "Registry password"
    required: true
  
runs:
  using: "composite"
  steps:
  - name: Login to Container Registry
    uses: docker/login-action@v1
    with:
      registry: ${{ inputs.registry_host }}
      username: ${{ inputs.registry_username }}
      password: ${{ inputs.registry_password }}

  - name: Compose build ${{ inputs.component }}
    shell: bash
    run: sudo -E docker-compose build ${{ inputs.component }}
    working-directory: ./src
    env:
      TAG: latest
      REGISTRY_ENDPOINT: ${{ inputs.registry_endpoint }}

  - name: Compose push ${{ inputs.component }}
    shell: bash
    run: sudo -E docker-compose push ${{ inputs.component }}
    working-directory: ./src
    env:
      TAG: latest
      REGISTRY_ENDPOINT: ${{ inputs.registry_endpoint }}