name: admin
ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
  hosts:
    - host: admin.ecommerce-store-builder.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: admin-tls
      hosts:
        - admin.ecommerce-store-builder.com