name: frontend_management_deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - deploy
  push:
    branches:
      - main
    paths:
      - deploy/frontend.yaml
      - deploy/frontend-management.yaml

env:
  COMPONENT_NAME: management
  COMPONENT_TYPE: frontend
  K8S_CLUSTER: saas
  K8S_NAMESPACE: saas-app-development

jobs:

  deploy:
    runs-on: ubuntu-latest    
    environment: development    
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/deploy
        with:
          digitalocean_access_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          component_name: ${{ env.COMPONENT_NAME }}
          component_type: ${{ env.COMPONENT_TYPE }}
          k8s_cluster: ${{ env.K8S_CLUSTER }}
          k8s_namespace: ${{ env.K8S_NAMESPACE }}