name: frontend_management_config

on:
  push:
    branches:
      - main
    paths:
      - deploy/app/config/environments/common.yaml
      - deploy/app/config/environments/development.yaml
      - deploy/app/config/frontends/common.yaml
      - deploy/app/config/frontends/management/common.yaml
      - deploy/app/config/frontends/management/development.yaml

env:
  COMPONENT_NAME: management
  COMPONENT_TYPE: frontend

jobs:

  deploy:  
    environment: development
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/deploy
        with:
          environment: development
          component_name: ${{ env.COMPONENT_NAME }}
          component_type: ${{ env.COMPONENT_TYPE }}
          digitalocean_access_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}